config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'users', only: [:create] do
    resource :password,
      controller: 'clearance/passwords',
      only: [:create, :edit, :update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/create_user' => 'clearance/users#new', as: 'create_user'

  resources :passwords, controller: 'clearance/passwords', only: [:create, :new, :update]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :companies

  resources :jobs
  root 'companies#index'

  namespace :authenticated do
      get 'companies' => 'admin#companies'
      get 'jobs' => 'admin#jobs'
  end

  namespace :api do
    namespace :v1 do
      resources :users, controller: 'users', only: [:create]
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
	mount_uploader :company_logo, PictureUploader
	validates :company_profile, presence: true
	validates_format_of :hr_email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, uniqueness: true, :on => [:create]
	validates :company_name, presence: true, uniqueness: true
	validates :technology_stack, presence: true
	validates :culture, presence: true
	validates :team_info, presence: true
	store_accessor :talent_requirements

	enum status: {
	    'pending_approval' => 0,
	    'partner_company' => 1,
	    'rejected' => 2
  	}
end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, presence: true
  	validates :job_description, presence: true
  	validates :location, presence: true
  	validates :employment_terms, presence: true
  	store_accessor :employment_terms
  	validates_format_of :job_poster_email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, :on => [:create]

  	enum status: {
  		'pending_approval' => 0,
  		'approved' => 1,
  		'rejected' => 2
  	}
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  enum role: {
  	"student" => 0,
  	"employer" => 1,
  	"admin" => 2
  }
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
	skip_before_action :verify_authenticity_token
	skip_before_action :require_login


	def create
		if request.env[:HTTP_TOKEN] == ENV['access_token']
			create_user
		else
			render json: {success: 'false', message: 'Token authentication failed!'}, status: 401
		end
	end

	private

		def create_user
			@user = User.new(email: params[:email], password: generate_password)
			if @user.save
				#insert action mailer here!
				render json: {success: 'true', message: "User created successfully."}, status: 200
			else
				render json: {success: 'false', message: 'Unable to create user, please check with admin.'}, status: 500
			end
		end

		def generate_password
			(0...8).map { (65 + rand(26)).chr }.join
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
end

app/controllers/authenticated/admin_controller.rb
class Authenticated::AdminController < ApplicationController
	before_action :require_admin
	
	def companies
		@companies_per_page = 12
		@companies = Company.where(status: 0).page(params[:page]).per(@companies_per_page)
	end

	def jobs
		@jobs_per_page = 12
		@jobs = Job.where(status: 0).page(params[:page]).per(@jobs_per_page)
	end

	private

		def require_admin
			if current_user.admin? == false
				raise ActionController::RoutingError.new('Not Found') 
				#fake 404 for security reasons
			end
		end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
  	@companies_per_page = 10
    @companies = Company.where(status: 1).page(params[:page]).per(@companies_per_page)
     # only approved companies get shown in index
  end

  def new
  	@company = Company.new
    authorize @company
  end

  def create
  	@company = Company.new(company_params)
    authorize @company
  	if @company.save
  		flash[:success] = "Awesome, your company submission will be displayed upon approval."
  		redirect_to sign_up_path
  	else
  		flash[:error] = "Submission failed, please ensure that the company details are input correctly."
  		render "new"
  	end
  end

  def update
    @company = Company.find(params[:id])
    authorize @company
    @company.update(company_params)
    if @company.save
      flash[:success] = "Company status updated!"
    else
      flash[:error] = "Company status failed to update."
    end
    redirect_to authenticated_companies_path
  end

  private

	  def company_params
	  	params.require(:company).permit(:company_logo, :company_profile, :company_name, :hr_email, {:talent_requirements => []}, :status, :company_url, :technology_stack, :culture, :team_info)
	  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  	@jobs = Job.where(status: 1).page(params[:page]).per(25)
  end

  def new
  	@job = Job.new
    authorize @job
  end

  def create
  	@job = Job.new(job_params)
    authorize @job
  	if @job.save
  		flash[:success] = "Admin notified, your job post will be visible once approved."
  		redirect_to root_path
  	else
  		flash[:error] = "Job failed to create! Make sure all fields are correctly filled up."
  		render "new"
  	end
  end

  def update
    @job = Job.find(params[:id])
    authorize @job
    @job.update(job_params)
    if @job.save
      flash[:success] = "Job status updated!"
    else
      flash[:error] = "Job status failed to update."
    end
    redirect_to authenticated_jobs_path
  end

  private

	  def job_params
	  	params.require(:job).permit(:title, :job_description, :location, :job_poster_email, :company_name, {:employment_terms => []}, :status)
	  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	def create
		@user = User.new(user_params)
		authorize @user
		if @user.save
			flash[:success] = "Awesome, #{@user.role} user account has been created."
			redirect_to root_path
		else
			flash[:error] = "Failed to create an account, please try again."
			redirect_to create_user_path
		end
	end

	private
		def user_params
			params.require(:user).permit(:email, :password, :role)
		end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
	  base_title = "Next Academy Employment Portal"
	  page_title.empty? ?  base_title : "#{base_title} | #{page_title}"
	end
end

app/helpers/authenticated/admin_helper.rb
module Authenticated::AdminHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authenticated/admin/companies.slim
h3 
  | Partner Companies Approval Dashboard
div.row
- if @companies.count == 0
    p No more submissions need approval!
- else
  - @companies.each do |company|
    div.col.s12.m6
      div.card.medium
        div.card-image.waves-effect.waves-block.waves-light
      	 = image_tag(company.company_logo, :class => "activator") if company.company_logo.present?
        div.card-content
          span.card-title.activator.grey-text.text-darken-4
            = company.company_name
            i.material-icons.right
              | more_vert
          p = link_to company.company_url
        div.card-reveal
          span.card-title.grey-text.text-darken-4
            i.material-icons.right
              | more_vert
            = company.company_name
          p
            = company.company_profile
          p
            | Hiring manager email 
            = company.hr_email
            = simple_form_for(company, html: {class: 'form-inline', method: :put }) do |form|
              = form.input :status, label: "Current Status", as: :select, collection: Company.statuses.keys.to_a, input_html: { class: "input-field col m6 dropdown"}
              = form.button :submit

p = paginate @companies

app/views/authenticated/admin/jobs.slim
h3 
  | Job Posting Approval Dashboard
div.row
- if @jobs.count == 0
    p No more submissions need approval!
- else
  - @jobs.each do |job|
    div.col.s12.m6
      div.card.grey.darken-1
        div.card-content.white-text
          span.card-title
            => job.title
            | at
            =< job.company_name
          p
            | Job Description :
          blockquote
            = job.job_description
          p
            | Contact Email :
          blockquote
            = job.job_poster_email
          div.card-action
            | Employment terms
            - job.employment_terms.each do |term|
                - input = term.keys.first.gsub(/[^0-9A-Za-z]/, '')
                blockquote
                  = input
            = simple_form_for(job, html: {class: 'form-inline', method: :put }) do |form|
              = form.input :status, label: "Current Status", as: :select, collection: Job.statuses.keys.to_a, input_html: { class: "input-field col m6 dropdown"}
              = form.button :submit

p = paginate @jobs

app/views/companies/_company_form.slim
= simple_form_for(@company) do |form|
  = form.input :company_name, label: "Company Name"
  = form.input :company_profile, label: "Tell us what you do in 200 words or less.", as: :text
  = form.input :technology_stack, label: "Tell us your technology stack."
  = form.input :culture, label: "Tell us more about your company culture.", as: :text
  = form.input :team_info, label: "Tell us about your engineering team.", as: :text
  = form.input :hr_email, label: "Human Resources email"
  = form.input :company_url, label: "Company website"
  = form.label "What experience do you need from talents?", wrapper_html: {class: 'label'}
  p
    = form.collection_check_boxes :talent_requirements, [[{'Test Driven Development' => true}, 'Test Driven Development'], [{'Refactor Day' => true}, 'Refactor Day'], [{'Stand Ups' => true}, 'Stand-Ups']], :first, :last, wrapper_html: {class: 'new-row'}, include_hidden: false
  p
    = form.input :company_logo, label: "Company Logo", as: :file
  p
    = form.button :submit

app/views/companies/index.html.slim
- content_for(:title, 'Partner Companies')
h3
  | Our partner companies
div.row
    - @companies.each do |company|
        div.col.s12.m6
          div.card.large.black
          	div.card-image.waves-effect.waves-block.waves-light
              = image_tag(company.company_logo, :class => "responsive-img menu_icon activator") if company.company_logo.present?
            div.card-content
              span.card-title.activator.white-text.text-darken-4
                = company.company_name
                i.material-icons.right
                  | more_vert
              div.card-action
                p.white-text
                  | Technology stack :
                p.white-text
                  =< company.technology_stack
            div.card-reveal
              span.card-title.activator.grey-text.text-darken-4
                i.material-icons.right
                  | more_vert
                = company.company_name
              p
                | Profile : 
              p
                = company.company_profile
              p
                | Culture : 
              p
                = company.culture
              p
                | About their engineering team : 
              p
                = company.team_info
              p 
                | Required Experience : 
                - company.talent_requirements.each do |requirement|
                  - input = requirement.keys.first.gsub(/[^a-zA-Z\d\s:]/, '')
                  blockquote
                    = input
              h5
                | How to apply :
              p
                | Email your CV to 
              
                => company.hr_email
              - if company.company_url.present?
                p 
                  | or visit their website 
                  = link_to company.company_url

p = paginate @companies

app/views/companies/new.slim
- content_for(:title, 'Company Registration')
h3 Get your company registered to post jobs!

= render 'company_form'

app/views/jobs/_job_form.slim
= simple_form_for(@job) do |form|
  = form.input :title, label: "Job title"
  = form.input :job_description, label: "Job description", :input_html => { :rows => 10 }, as: :text, placeholder: "In 150 words or less, please explain the role and expectations of the applicant."
  = form.input :location, label: "Job location", placeholder: "City & State"
  = form.label "What are the employment terms?", wrapper_html: {class: 'label'}
  p
  = form.collection_check_boxes :employment_terms, [[{'Freelance' => true}, 'Freelance'], [{'Temp' => true}, 'Temp Staff'], [{'Permanent' => true}, 'Permanent']], :first, :last, include_hidden: false
  = form.input :company_name, label: "Name of company"
  = form.input :job_poster_email, label: "Your contact email"
 
  = form.button :submit

app/views/jobs/index.html.slim
- content_for(:title, 'Job Postings')
h3
  | Jobs Openings 
div.row
    - @jobs.each do |job|
      div.col.s12.m6
        div.card.grey.darken-1
          div.card-content.white-text
            span.card-title 
              => job.title
              | at
              =< job.company_name
            p
              | Job Description :
            blockquote
              = job.job_description
            p
              | Contact Email :
            blockquote
              = job.job_poster_email
            div.card-action
              | Employment terms
              - job.employment_terms.each do |term|
                - input = term.keys.first.gsub(/[^a-zA-Z\d\s:]/, '')
                blockquote
                  = input

p = paginate @jobs

app/views/jobs/new.slim
- content_for(:title, 'Post A Job')
h3 Looking To Hire? Post A Job Here!

= render 'job_form'

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper grey darken-3">
      <a href="#" data-activates="mobile-demo" class="right button-collapse"><i class="material-icons">menu</i></a>
      <img src="https://www.nextacademy.com/assets/next-academy-white-4ed0878af28fe9425294f5834b9fa5364e10cee1b968c5e97277235458470c85.png" width="141" height="50" style="margin-top: 7px;">
      <!-- desktop -->
      <ul class="right hide-on-med-and-down">
        <% if signed_in? %>    
          <li>
            <%= link_to t(".partner-companies"), root_path %>
          </li>
          <li>
            <%= link_to t(".jobs-board"), jobs_path %>
          </li>
          <% if current_user.admin? %>
            <li>
              <%= link_to t(".create_user"), create_user_path %>
            </li>
          <% end %>
        <% end %>
        <% if signed_in? && (current_user.employer? || current_user.admin?)  %>
          <li>
            <%= link_to t(".create-a-job"), new_job_path %>
          </li>
          <li>
            <%= link_to t(".create-company-profile"), new_company_path %>
          </li>
        <% end %>
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-button" href="#" data-activates="dropdown" data-beloworigin="true" data-constrainwidth="false">Account<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
      </ul>
      <!-- mobile -->
      <ul class="side-nav" id="mobile-demo">
        <% if signed_in? %>    
          <li>
            <%= link_to t(".partner-companies"), root_path %>
          </li>
          <li>
            <%= link_to t(".jobs-board"), jobs_path %>
          </li>
        <% end %>
        <% if signed_in? && (current_user.employer? || current_user.admin?)  %>
          <li>
            <%= link_to t(".create-a-job"), new_job_path %>
          </li>
          <li>
            <%= link_to t(".create-company-profile"), new_company_path %>
          </li>
        <% end %>
        <% if signed_in? %>
          <% if current_user.admin? %>
            <li>
              <%= link_to t(".job-approval"), authenticated_jobs_path %>
            </li>
            <li>
              <%= link_to t(".company-approval"), authenticated_companies_path %>
            </li>
            <li>
              <%= link_to t(".create_user"), create_user_path %>
            </li>
          <% end %>
            <li>
              <%= link_to t(".change-password"), edit_user_password_path(current_user.id) %>
            </li>
            <li>
              <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
            </li>
        <% end -%>
      </ul>
  </div>
</nav>
<!-- Dropdown Structure -->
<ul id="dropdown" class="dropdown-content collection">
  <% if signed_in? %>
    <% if current_user.admin? %>
      <li class="collection-item">
        <%= link_to t(".job-approval"), authenticated_jobs_path %>
      </li>
      <li class="collection-item">
        <%= link_to t(".company-approval"), authenticated_companies_path %>
      </li>
    <% end %>
      <li class="collection-item">
        <%= link_to t(".change-password"), edit_user_password_path(current_user.id) %>
      </li>
      <li class="collection-item">
        <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
      </li>
  <% end -%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title)%></title>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="header">
      <%= render :partial => 'layouts/navbar' %>
    </div>

    <div class="container">
      
      <div id="flash">
        <% flash.each do |key, value| -%>
          <div class="flash <%= key %>"><%=h value %></div>
        <% end %>
      </div>

      <%= yield %>

    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="role-field">
  <%= form.label :role %>
  <%= form.select(:role, ['employer', 'student'], {}, {:class => 'dropdown' }) %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit class: "btn btn-default" %>
    </div>

</div>